
const HomeApi=[
    {
        id:1,
        image:'/images/restaurant.jpg',
        alt:'restaurant',
        title:'Simple Restaurant Menu Project',
      
        details:[
            {info:'Ui Bootstrap' },
            {info:'Usestate'},
            {info:'Map'},
            {info:'Api Object'},
            {info:'filter'},
            {info:'props'},
        ],
        btn1:"/restaurant",
        btn:'Click here to Restaurant Project',
        btn2:'',
    },
    {
        id:2,
        image:'/images/incdecbtn.png',
        alt:'incdecbtn',
        title:'Icre-Decrement Project',
        details:[
            {info:'Ui Bootstrap' },
            {info:'Usestate'},
            {info:'Ternary Operator'},
            {info:'UseReducer'},
        ],
        btn1:"/usestate",
        btn2:"/usereducer",
        btn:'Click here to Icre-Decrement Project',
    },
    {
        id:3,
        image:'/images/todolist.png',
        alt:'todolist',
        title:'Todo List Intermediate Project',
      
        details:[
            {info:'Ui Bootstrap' },
            {info:'useState'},
            {info:'Spread Operator'},
            {info:'Map'},
            {info:'useEffect'},
            {info:'filter'},
            {info:'find'},
            {info:'CRUD'},
            {info:'localStorage'},
        ],
        btn1:"/todomain",
        btn:'Click here to Todo List Project',
        btn2:'',
    },
    {
        id:4,
        image:'/images/advtodolist.png',
        alt:'advtodolist',
        title:'Todo List Adv',
      
        details:[
            {info:'...previous' },
            {info:'Object Create'},
        
        ],
        btn1:"/advtodomain",
        btn:'Click here to Adv Todo List Project',
        btn2:'',
    },
    {
        id:5,
        image:'/images/weather.png',
        alt:'advtodolist',
        title:'Open Weather Real Api Project',
      
        details:[
            {info:'useState, useEffect, map' },
            {info:'async'},
            {info:'switch statement'},
            {info:'object destructuring'}
        
        ],
        btn1:"/weather",
        btn:'Click here to Real Api Weather Project',
        btn2:'',
    },
    {
        id:6,
        image:'/images/incdecbtn.png',
        alt:'advtodolist',
        title:'Increment Decrement Class Component Project',
      
        details:[
            {info:'this.setState' },
            {info:'componentDidMount()'},
            {info:'componentDidUpdate()'},
        ],
        btn1:"/incdec",
        btn:'inc dec',
        btn2:'',
    },
    {
        id:7,
        image:'/images/todolist.png',
        alt:'advtodolist',
        title:'Todo List Class Component Project',
      
        details:[
            {info:'this.setState' },
            {info:'map,find,filter function'},
        ],
        btn1:"/classtodolist",
        btn:'Todo List ',
        btn2:'',
    },
    {
        id:8,
        image:'/images/weather.png',
        alt:'advtodolist',
        title:'Weather Class Component Project',
        details:[
            {info:'this.setState' },
            {info:'map,find,filter function'},
        ],
        btn1:"/classweathermain",
        btn:'Weather Api ',
        btn2:'',
    },
    {
        id:9,
        image:'/images/formfirebase.PNG',
        alt:'advtodolist',
        title:'Contact Us Firebase',
        details:[
            {info:'Functional Component'},
            {info:'beauty css style' },
            {info:'firebase real time database'},
            {info:'store data on firebase'},
        ],
        btn1:"/contactus",
        btn:'Go to Contact Us ',
        btn2:'',
    },
    {
        id:10,
        image:'/images/advtodolist.png',
        alt:'todolist',
        title:'Knowledge Use Reducer',
        details:[
            {info:'Functional Component'},
            {info:'beauty css style' },
            {info:'firebase real time database'},
            {info:'store data on firebase'},
        ],
        btn1:"/userReducerComplete",
        btn:'Use Reducer ',
        btn2:'',
    },
    {
        id:11,
        image:'/images/FirebaseComp.png',
        alt:'firebase',
        title:'Complete Firebase Concepts',
        details:[
            {info:'CRUD'},
            {info:'authentication' },
            {info:'batch large data store'},
            {info:'shop api'},
            {info:'spinner with hoc'},
        ],
        btn1:"/completefirebase",
        btn:'Complete Firebase',
        btn2:'',
    },
    {
        id:11,
        image:'',
        alt:'hoc',
        title:'High Order Component',
        details:[
            {info:'hoc with different api'},
        ],
        btn1:"/hoc",
        btn:'HOC',
        btn2:'',
    },
    {
        id:12,
        image:'',
        alt:'thunk',
        title:'Thunk Concepts',
        details:[
            {info:'thunk middleware async'},
        ],
        btn1:"/thunkapp",
        btn:'Redux Thunk Pattern',
        btn2:'',
    },
]
export default HomeApi;